apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  # INSTRUCTIONS: Convert your actual values to Base64 and paste them inside the quotes below.
  
  jwt: "YOUR_JWT_SECRET_KEY_BASE64"
  
  # Cloudinary Credentials
  CLOUDINARY_CLOUD_NAME: "YOUR_CLOUDINARY_CLOUD_NAME_BASE64"
  CLOUDINARY_API_KEY: "YOUR_CLOUDINARY_API_KEY_BASE64"
  CLOUDINARY_API_SECRET: "YOUR_CLOUDINARY_API_SECRET_BASE64"
  
  # MongoDB Credentials
  MONGO_INITDB_ROOT_USERNAME: "YOUR_MONGO_ROOT_USERNAME_BASE64"
  MONGO_INITDB_ROOT_PASSWORD: "YOUR_MONGO_ROOT_PASSWORD_BASE64"